### ISSUE TITLE
Missing vextab-jison.js file when installed from npm

### ISSUE THREAD

**Issue by seanwash** [0xfe/vextab#72]
```
Error: Cannot find module '../build/vextab-jison.js' from '/Users/seanwash/Sites/fg-app/node_modules/vextab/src'
  at /Users/seanwash/Sites/fg-app/node_modules/resolve/lib/async.js:55:21
  at load (/Users/seanwash/Sites/fg-app/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/seanwash/Sites/fg-app/node_modules/resolve/lib/async.js:92:31)
  at /Users/seanwash/Sites/fg-app/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```
Browserify, installed vextab via npm.

**Comment by seanwash** [comment]
Alllright, after some digging around I see that this has already been discussed a bit in #53. For now I just ran the build step manually and things are good to go. For what it's worth though it would have been helpful if it were mentioned in the readme somewhere :)
